version: '3.6'

services:
    nginx:
        image: nginx
        ports:
            - '127.0.0.1:1235:80'
        volumes:
            - './nginx/html:/usr/local/nginx/html'
            - './nginx/nginx.conf:/etc/nginx/nginx.conf'
        restart: unless-stopped
        depends_on:
            - nodejs
        networks:
            - ss-backend

    nodejs:
        build:
            context: ./nodejs
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - ss-backend

networks:
    ss-backend: